### ISSUE TITLE
issues installing

### ISSUE THREAD

**Issue by powerplyer** [01org/fiovisualizer#3]
Hello I am new to this, however when I try to run python setup.py install I get the following error. I have installed all the dependencies as instructed however I have no idea where to get the fio-visualizer.py. 

[root@localhost fiovisualizer]# python setup.py install
running install
running bdist_egg
running egg_info
writing Fio_Visualizer.egg-info/PKG-INFO
writing top-level names to Fio_Visualizer.egg-info/top_level.txt
writing dependency_links to Fio_Visualizer.egg-info/dependency_links.txt
writing entry points to Fio_Visualizer.egg-info/entry_points.txt
error: package directory 'fiovisualizer' does not exist
[root@localhost fiovisualizer]#

**Comment by AndreyKudryavtsev** [comment]
Hi, thanks for the report, I'll check the installation script later. Can you run it just straight from the installation directory? 
python ./fio_visualizer.py

**Comment by powerplyer** [comment]
It looks like an awesome script. Here is the error if I run ./fio_visualizer.py.

[root@localhost fiovisualizer-master]# ./fio_visualizer.py 
Traceback (most recent call last):
  File "./fio_visualizer.py", line 1249, in <module>
    ui.setup_ui(window)
  File "./fio_visualizer.py", line 238, in setup_ui
    self.gridLayout_8.setMargin(3)
AttributeError: 'PySide.QtGui.QGridLayout' object has no attribute 'setMargin'
[root@localhost fiovisualizer-master]# 

Hope this helps

**Comment by powerplyer** [comment]
hello AndreyKudryavtsev any update would be awsome.

**Comment by AndreyKudryavtsev** [comment]
seems you simply don't have PyQt or pyqtgraph installed. Did you check the readme for the manual installation steps?

**Comment by powerplyer** [comment]
ok thank you I will double check.

**Comment by powerplyer** [comment]
thanks for all you help, started all over again and it is now working. This is an awsome tool, look forward to more NMVe FIO scripts.

**Comment by AndreyKudryavtsev** [comment]
Thank you!
