### ISSUE TITLE
Please link this page url on FIO visualizer page.

### ISSUE THREAD

**Issue by hiroyuki-sato** [01org/fiovisualizer#5]
Hello 

I know this tool on this page. https://01.org/fio-visualizer
But I can't find this github page on that page.

There are many documentations on this page.
Please add https://github.com/01org/fiovisualizer URL link on 
https://01.org/fio-visualizer page.

Thanks

**Comment by AndreyKudryavtsev** [comment]
Hello Hiroyuki-sato, 
I agree with you, the page design is confusing but the link is there - in the right top corner you'll see "Git Repo" sign.

**Comment by hiroyuki-sato** [comment]
Oh!, I see. It's gray color!!. 😢
It's hard to find this link. 

Anyway thanks!!.
